# Generated by Django 3.2.8 on 2023-10-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractionregistration',
            name='pain_measurement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
